---
- name: Install python packages for fan control.
  become: yes
  ansible.builtin.apt:
    name:
      - python3-psutil
      - python3-lgpio
      - git
    state: present

- name: Clone a github repository
  become: yes
  ansible.builtin.git:
    repo: https://github.com/stkr22/raspberry-pi-pwm-fan-control.git
    dest: /opt/pwm-fan-control
    single_branch: yes
    version: main
    force: yes

- name: Install pwm fan cronjob.
  become: yes
  ansible.builtin.cron:
    name: "adjust fan"
    job: "/usr/bin/python3 -u /opt/pwm-fan-control/fan.py --min-temp={{ fan_control_config.min_temp }} --max-temp={{ fan_control_config.max_temp }} --fan-low={{ fan_control_config.fan_low }} --fan-high={{ fan_control_config.fan_high }} --wait-time=-1 --pwm-gpio={{ fan_control_config.pwm_gpio }} --pwm-freq={{ fan_control_config.pwm_freq }}"
  when: fan_script_mode 

- name: Add Python pwm fan control service.
  become: yes
  ansible.builtin.template:
    src: lgpio-fan-control.service.j2
    dest: /etc/systemd/system/lgpio-fan-control.service
    owner: root
    group: root
    mode: 0644
  when: not fan_script_mode

- name: Enable service python pwm fan control and start it.
  become: yes
  ansible.builtin.systemd:
    name: lgpio-fan-control
    state: started
    enabled: yes
    daemon_reload: yes
  when: not fan_script_mode
