---
- name: Install python packages for fan control.
  ansible.builtin.apt:
    name:
      - python3-psutil
      - python3-lgpio
      - git
    state: present

- name: Clone a github repository
  ansible.builtin.git:
    repo: https://github.com/stkr22/raspberry-pi-pwm-fan-control.git
    dest: /opt/pwm-fan-control
    single_branch: yes
    version: main
    force: yes

- name: Add Python pwm fan control service.
  ansible.builtin.template:
    src: lgpio-fan-control.service.j2
    dest: /etc/systemd/system/lgpio-fan-control.service
    owner: root
    group: root
    mode: 0644

- name: Enable service python pwm fan control and start it.
  ansible.builtin.systemd:
    name: lgpio-fan-control
    state: started
    enabled: yes
    daemon_reload: yes
